viliproject/vili

sample_devenv.sh

Correctly matches the required and suggested environment variables for
running vili

Updates contents of sample_devenv.sh

---

api/deployer.go
api/deployments.go
api/runner.go
docker/docker.go
docker/ecr.go
docker/ecr_test.go
docker/registry.go
docker/registry_test.go

Also fix a few miscellaneous logging and tracking issues with deployment
revisions/UIDs.

Use full branch-qualified docker image names in deployments+jobs

---

api/apps.go
api/deployer.go
api/utils.go
kube/v1/types.go

Allows for use of configmap environment variables

Update kubernetes type definitions to v1.2 k8s

---

public/src/jobs/JobRuns.jsx

Remove empty "From Tag" column, rename "To Tag" to "Tag"

Minor cleanup on jobs runs page

---

api/api.go
app/app.go
app/slackbot.go
app/vili.go
config/app.go
kube/deployments.go
kube/kube.go
kube/nodes.go
kube/pods.go
kube/replicasets.go
kube/services.go
sample_devenv.sh
slack/slack.go
templates/github.go
util/util.go

Adds a `DEFAULT_ENV` variable for specifying which preconfigured
environment to fall back on when resolving kubernetes client config and
template paths.

Auto-detect environments from kubernetes namespaces

---

api/api.go
api/apps.go
api/jobs.go
docker/docker.go
docker/ecr.go
docker/ecr_test.go
docker/registry.go
docker/registry_test.go
environments/environments.go
public/src/nav/TopNav.jsx

Also do not error out when loading docker images as long as retrieving
at least one of the given branches is successful

Allow deploying docker images from environment branches

---

api/deployer.go
api/deployments.go
app/app.go
public/src/envs/EnvCreateModal.jsx
public/src/lib/viliapi.js

Sets desiredReplicas=1 for each deployed app
Prefers the feature environment's default branch when selecting the image to deploy, falls back to the most recent image from master or develop
After creating environment and pressing the "Deploy Apps" button:
After pressing "Confirm": (red indicates failure)

Auto-deploy apps in a newly-created environment

---

public/src/envs/EnvCreateModal.jsx

Need to update bluebird promises :(

Create an app's service before deploying the app in a new env

---

public/src/envs/EnvCreateModal.jsx

Also disable the Confirm button for both jobs and apps until all
jobs/apps are properly loaded.

Run jobs before deploying apps in new environment

---

api/apps.go
api/deployer.go
kube/pods.go
kube/replicasets.go
public/src/apps/App.jsx
public/src/apps/AppsList.jsx

Previously this showed the creation timestamp for the deployment, which
only indicates when the app deployment was first created. Now this
instead shows the creation timestamp of the most recent replica set.

Show correct "deployed at" time for deployments

---

api/apps.go

Fix loading replica sets for all apps for an environment

---

app/app.go
app/slackbot.go
environments/environments.go
public/src/apps/AppsList.jsx
public/src/envs/EnvCreateModal.jsx
public/src/nav/SideNav.jsx
slack/slack.go

Expects messages of the form:
Published (comma separated app/job list) with tag (tag) from branch
(branch).
Allows for bulk auto-deploys and auto-job runs.
Associates apps and jobs with environments instead of loading this
separately on frontend app load.

Slackbot can parse and react to messages announcing published images

---

api/apps.go
api/deployer.go
api/deployments.go
api/environments.go
api/jobs.go
api/runner.go
environments/environments.go
templates/github.go
templates/templates.go

Fall back to the default branch (usually master) for loading these
templates

Load apps/jobs templates in the appropriate branch for the environment

---

README.md

Just deployed this to heroku: https://vili-slackin.herokuapp.com/

Add slack badge to README

---

environments/environments.go

Specifically load apps and jobs for environments which have a different
name than the namespace in kubernetes
Also prevent potential concurrent map write

Fix loading apps and jobs for environments

---

public/src/apps/AppDeployment.jsx

Use FormControl instead of Input tag

Fix AppDeployment dropdown

---

vendor/github.com/niccaluim/viper/viper.go

This backports two vendored changes we've made in a private repo but
haven't had time to make good enough to submit upstream.
Original comments for context:
This was (at least to me) some non-obvious behavior but multiple config
paths weren't supported by our viper change. Meaning the two
viper.AddConfigPath lines at the start of pkg/config/config.go don't
do at all what it looks like.
Upstream has a mergeMaps implementation that seems good so I've
borrowed that here to merge multiple paths into a single config.

Backport vendored viper changes

---

api/deployments.go
circle.yml
public/src/apps/AppPods.jsx

This allows Deployments of zero size (used for templates) or to scale a
Deployment to zero (to turn off a service)
@BrianBland

Remove special case for zero

---

public/src/apps/AppPods.jsx

Fix error in webpack build

---

public/src/nav/TopNav.jsx

Fix a bug where the prod topnav dropdown would not have the black background, and the text would not be legible against the "warning" stripes.

Fix navbar prod CSS

---

public/package.json
public/src/apps/AppSpec.jsx
public/src/jobs/JobSpec.jsx
public/src/less/app.less

Remove highlight.js to prevent
```
Uncaught Error: Cannot find module "./languages/autoit"
```

Remove highlight.js

---

public/src/apps/AppsList.jsx

Fix the approve all and unapprove all buttons on the apps list page

---

.circleci/config.yml

This PR fixes the CircleCI configuration file

Fix CircleCI configuration

---

api/deployments.go
kube/client.go

This PR fixes an issue with scaling deployments

Fix deployment scaling

---

environments/environments.go

Periodically reconnect to the namespaces "watch" endpoint to ensure that
new environments are not missed.

Improve watching of kubernetes namespaces

---

Dockerfile
public/src/containers/releases/ReleasesList.js

Fix history in the releases history page that was causing an error to be thrown when creating a new release.

Fix history in the releases history page

---

README.md
api/ciprovider.go
api/releases.go
api/rollouts.go
app/vili.go
circleci/circleci.go
config/app.go
sample_devenv.sh
vendor/github.com/jszwedko/go-circleci/LICENSE
vendor/github.com/jszwedko/go-circleci/circleci.go
vendor/manifest

This PR:
- Adds a webhook execution to run after successful release deployment.
- Creates a circleci client in Vili to interact with circleci api.

Deployment detection to run forseti tests automatically

---

api/ciprovider.go
app/vili.go
auth/basic.go
config/app.go
functions/functions.go
sample_devenv.sh

Allow basic auth as an authentication mechanism to vili.

Add support for basic auth
